### ISSUE TITLE
Confusing error from undefined step with percent sign

### ISSUE THREAD

**Issue by cbandy** [sittercity/gocumber#2]
An undefined step containing `%` prints poorly. For example,

```gherkin
When I get "/something/%{UUID}"
```

Causes the following output:
```
        gocumber.go:95: Undefined step:
                When I get "/something/%!{(MISSING)UUID}"
```

`t.Errorf()` should be `t.Error()`.

**Comment by ptrimble** [comment]
Handled in https://github.com/sittercity/gocumber/pull/3
