### ISSUE TITLE
Should we rename repo to indicate v1?

### ISSUE THREAD

**Issue by ptrimble** [sittercity/gocumber#4]
What do we think about renaming this repo now to put -v1 in the name? This way when we make breaking changes we can clone to a new repo with a new name, thereby allowing people to upgrade gracefully.

I've seen this in a few places but I can't find them now. Thoughts?

**Comment by zombor** [comment]
I don't think so. Versioning is not something the repo location itself should do, imo. We should use semantic versioning standalone, and let third parties determine how that works.

You are probably referring to this: http://labix.org/gopkg.in

We can support this without polluting our names.

**Comment by ptrimble** [comment]
Could you walk me through how you envision us releasing breaking changes? I'm having a hard time understanding what 'semantic versioning standalone' means.

**Comment by zombor** [comment]
The same-ish way we do with ruby gems: we informally specify the version in a version file. We can "formally" specify it with a tag also. There's no "official" way to do this with go (which isn't a bad thing), as opposed to in ruby with gemspec files. The consumer of the code will need to be diligent about paying attention to new versions and what changed with them.

**Comment by ptrimble** [comment]
Well, we don't 'informally' specify the version with gems. I mean, we do have a 'version.txt' file but it is also baked into the gem itself and we lock to a specific version (or major version, generally) with Bundler. 

With Go we are basically doing nothing: we push a breaking change, someone pulls down with Godep (for example), and their code breaks. Saying that the consumer of the code must be diligent is basically saying that they are going to have to deal with breaking changes as they come up and they won't have any option but to move forward, right then, if they want their code to compile. There is no way for the person to 'go back' to a version that works with their code so they can upgrade in a controlled way.

I recognize that the Go community has no 'official' way to do it and I also agree that it's not necessarily a bad thing. It just makes me feel icky.

**Comment by ptrimble** [comment]
Mainly I don't see how doing what you specified above supports a way to push breaking changes without affecting our consumers. Can you help me understand what a consumer could do to protect themselves upon a breaking change being pushed to our repo?

**Comment by zombor** [comment]
> I mean, we do have a 'version.txt' file

Sure, this is what I meant.

> someone pulls down with Godep (for example), and their code breaks.

Nah, they look to see there was an update, they intelligently decide if they want to upgrade, then they do it. Blindly doing it is the same as doing `~> 0` in bundler, which is just stupid.

>  they are going to have to deal with breaking changes 

If we tag our repo with versions, the tool I linked to above can be used by consumers who want to use that kind of locking.

> I recognize that the Go community has no 'official' way to do it 

It's not that the "go community" doesn't have a way; the language itself doesn't have a way, by design. It's the same as in C or C++ or anything like that. You have code you import from the filesystem and that's that. The language has no opinion about it (and I actually like this).

> Mainly I don't see how doing what you specified above supports a way to push breaking changes without affecting our consumers. 

Well if someone is using gopkg.in, they are "locked" to that major version. The docs describe how this works.

> Can you help me understand what a consumer could do to protect themselves upon a breaking change being pushed to our repo?

If someone is just using `go get` to include this dependency, there's nothing we can do.

**Comment by ptrimble** [comment]
Aren't we 'blindly' pulling down packages via Godep when we run stuff on Jenkins? Am I misunderstanding what happens when we run `godep restore` on a clean system with no packages available locally?

Either way, gopkg.in seems to provide exactly what I want. From what I understand we would create branches named 'v1', 'v2', etc and people that want to lock would just use the service. That's fine for me.

**Comment by zombor** [comment]
> Aren't we 'blindly' pulling down packages via Godep when we run stuff on Jenkins? 

No, the godeps.json file specifies revisions to be pulled down for specific dependencies. That's why we use godeps :)

See: https://github.com/sittercity/gocumber/blob/master/Godeps/Godeps.json#L8
